import { Theme } from './types';

export const THEMES: Theme[] = [
  {
    id: 'old-money',
    name: 'Inherited Wealth',
    classes: {
      bg: 'bg-[#0c0a09]',
      textMain: 'text-stone-200',
      textMuted: 'text-stone-500',
      accent: 'text-amber-500',
      accentBg: 'bg-amber-500',
      accentBorder: 'border-amber-500/30',
      panel: 'bg-stone-900/40 backdrop-blur-md',
      panelBorder: 'border-white/5',
      fontHead: 'font-serif',
      fontBody: 'font-sans',
      buttonPrimary: 'bg-amber-700 hover:bg-amber-600 text-white shadow-[0_4px_14px_0_rgba(217,119,6,0.39)]',
      radius: 'rounded-sm',
      nav: 'bg-stone-950/80 border-b border-white/5',
    },
    chartColors: ['#d97706', '#059669', '#dc2626', '#2563eb', '#7c3aed'],
    buddyType: 'orb'
  },
  {
    id: 'sunday-brunch',
    name: 'Sunday Brunch',
    classes: {
      bg: 'bg-[#fafaf9]',
      textMain: 'text-stone-800',
      textMuted: 'text-stone-400',
      accent: 'text-rose-400',
      accentBg: 'bg-rose-400',
      accentBorder: 'border-rose-200',
      panel: 'bg-white/60 backdrop-blur-md shadow-sm',
      panelBorder: 'border-stone-200',
      fontHead: 'font-serif',
      fontBody: 'font-sans',
      buttonPrimary: 'bg-stone-800 hover:bg-stone-700 text-rose-100 shadow-md',
      radius: 'rounded-2xl',
      nav: 'bg-white/80 border-b border-stone-200',
    },
    chartColors: ['#fb7185', '#a8a29e', '#e7e5e4', '#f43f5e', '#881337'],
    buddyType: 'orb'
  },
  {
    id: 'princess',
    name: 'Spoiled Princess',
    classes: {
      bg: 'bg-fuchsia-50',
      textMain: 'text-fuchsia-900',
      textMuted: 'text-fuchsia-400',
      accent: 'text-pink-500',
      accentBg: 'bg-pink-400',
      accentBorder: 'border-pink-200',
      panel: 'bg-white/40 backdrop-blur-xl shadow-lg border border-pink-100',
      panelBorder: 'border-pink-100',
      fontHead: 'font-serif italic',
      fontBody: 'font-sans',
      buttonPrimary: 'bg-gradient-to-r from-pink-300 to-fuchsia-300 hover:from-pink-400 hover:to-fuchsia-400 text-white shadow-lg shadow-pink-200',
      radius: 'rounded-[2rem]',
      nav: 'bg-white/60 border-b border-pink-100',
    },
    chartColors: ['#ec4899', '#d946ef', '#f0abfc', '#86efac', '#fcd34d'],
    buddyType: 'heart'
  },
  {
    id: 'hustler',
    name: '8-Bit Hustler',
    classes: {
      bg: 'bg-slate-950',
      textMain: 'text-cyan-50',
      textMuted: 'text-slate-500',
      accent: 'text-green-400',
      accentBg: 'bg-green-500',
      accentBorder: 'border-green-500',
      panel: 'bg-slate-900/90 border-2 border-slate-800 shadow-none',
      panelBorder: 'border-slate-800',
      fontHead: 'font-mono tracking-tighter',
      fontBody: 'font-mono tracking-tight',
      buttonPrimary: 'bg-green-600 hover:bg-green-500 text-black border-b-4 border-green-800 active:border-b-0 active:translate-y-1',
      radius: 'rounded-none',
      nav: 'bg-slate-900 border-b-2 border-slate-800',
    },
    chartColors: ['#4ade80', '#22d3ee', '#f472b6', '#facc15', '#a78bfa'],
    buddyType: 'pixel'
  },
  {
    id: 'exam',
    name: 'Exam Season',
    classes: {
      bg: 'bg-[#fefce8]',
      textMain: 'text-blue-900',
      textMuted: 'text-blue-900/40',
      accent: 'text-red-600',
      accentBg: 'bg-blue-900',
      accentBorder: 'border-blue-900',
      panel: 'bg-yellow-100/50 backdrop-blur-sm border-2 border-dashed border-blue-900/20 shadow-md transform rotate-[0.5deg]',
      panelBorder: 'border-blue-900/10',
      fontHead: 'font-hand font-bold tracking-wider',
      fontBody: 'font-mono',
      buttonPrimary: 'bg-blue-900 text-yellow-50 hover:bg-blue-800 transform -rotate-1 shadow-md',
      radius: 'rounded-sm',
      nav: 'bg-[#fefce8] border-b-2 border-blue-900/10',
    },
    chartColors: ['#dc2626', '#1e3a8a', '#d97706', '#16a34a', '#4b5563'],
    buddyType: 'paper'
  },
  {
    id: 'monk',
    name: 'Financial Monk',
    classes: {
      bg: 'bg-white',
      textMain: 'text-stone-600',
      textMuted: 'text-stone-300',
      accent: 'text-emerald-500',
      accentBg: 'bg-emerald-100',
      accentBorder: 'border-emerald-100',
      panel: 'bg-stone-50 border border-stone-100 shadow-none',
      panelBorder: 'border-stone-100',
      fontHead: 'font-sans font-light',
      fontBody: 'font-sans font-light',
      buttonPrimary: 'bg-stone-200 hover:bg-stone-300 text-stone-600 rounded-lg',
      radius: 'rounded-xl',
      nav: 'bg-white/90 border-b border-stone-50',
    },
    chartColors: ['#10b981', '#6ee7b7', '#a7f3d0', '#d1fae5', '#ecfdf5'],
    buddyType: 'leaf'
  }
];